@extends('layout')
@section('title', 'Posts')
@section('content')
    <div class="show-div">
        <div class="container">
            <h2>Generated by
                @can('update', $post)
                    You
                @endcan
                :
                {{ $post->user->name }}
            </h2>
            <p>{{ $post->prompt }}</p>
            <img src='{{ url("images/$post->image_url") }}'' alt="">
            <div class="actions">
                @can('update', $post)
                    <a href="{{ route('posts.edit', ['post' => $post]) }}">Update</a>
                @endcan
                @can('delete', $post)
                    <form action="{{ route('posts.destroy', ['post' => $post->id]) }}" method="POST">
                        @csrf
                        @method('delete')
                        <input type="submit" value="Delete">
                    </form>
                @endcan
            </div>
        </div>
    </div>
@endsection
